apiVersion: batch/v1
kind: Job
metadata:
  name: testjob
spec:
  template:
    spec:
      containers:
        - name: testjob
          args:
            - -c
            - |
              echo "hello world from a job that will fail"
              sleep 10 && echo "expected-log-message" && echo "content" > /data/testfile.txt
              exit 1
