apiVersion: batch/v1
kind: Job
metadata:
  name: testjob
  labels:
    app: testapp
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: monitoring
      containers:
        - name: testjob
          image: busybox
          command:
            - sleep
            - "10"
          imagePullPolicy: IfNotPresent
        - name: jobber
          image: jobber
          args:
            - monitor
            - -n
            - testjob
            - -v
            - "1"
          env:
            - name: JOB_NAME
              value: testjob
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      restartPolicy: Never
