apiVersion: batch/v1
kind: Job
metadata:
  name: testjob
  labels:
    app: testapp
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: monitoring
      containers:
        - name: testjob
          image: busybox
          command:
            - sh
          args:
            - -c
            - |
              echo "hello world"
              sleep 10 && echo "done" && exit 1