apiVersion: skaffold/v2beta4
kind: Config
build:
  artifacts:
    - image: jobber
      custom:
        buildCommand: ./build.sh
        dependencies:
          paths:
            - .
profiles:
  - name: pass
    deploy:
      kustomize:
        paths:
          - ./kubernetes-resources/testjob/base
  - name: fail
    deploy:
      kustomize:
        paths:
          - ./kubernetes-resources/testjob/fail
